### PR TITLE
Integrate comms

### PR DESCRIPTION
**Pull request by caguero**
Requires:
  * https://github.com/ignitionrobotics/ign-gazebo/pull/1428
  * https://github.com/ignitionrobotics/ros_ign/pull/239

This pull requests integrates the comms model from Gazebo Sim. It adds the `CommsEndpoint` system to all models. The conventions used are:

* The address is the model name.
* The ROS 2 topic to send data is `<model_name>/tx`.
* The ROS 2 topic to receive data is `<model_name>/rx`.

How to test it?

1. Launch a world:
```
ros2 launch ros_ign_gazebo ign_gazebo.launch.py ign_args:="-v 4 -r simple_demo.sdf"
```

2. Spawn `quadrotor_1`:
```
ros2 launch mbzirc_ign spawn.launch.py name:=quadrotor_1 world:=simple_demo model:=mbzirc_quadrotor type:=uav x:=-0 y:=0 z:=1.2 R:=0 P:=0 Y:=0 slot3:=mbzirc_hd_camera
```

3. Spawn `quadrotor_2`:
```
ros2 launch mbzirc_ign spawn.launch.py name:=quadrotor_2 world:=simple_demo model:=mbzirc_quadrotor type:=uav x:=1 y:=1 z:=1.2 R:=0 P:=0 Y:=0 slot3:=mbzirc_hd_camera
```

4. Open a terminal and listen to the reception topic of `quadcopter_2`:
```
ros2 topic echo /quadrotor_2/rx
```

5. Open a terminal and send a message over the tx topic of `quadcopter_1`:
```
ros2 topic pub quadrotor_1/tx ros_ign_interfaces/Dataframe '{src_address: "quadrotor_1", dst_address: "quadrotor_2"}'
```

You should observe messages flowing.

### CODE REVIEW

**Comment by iche033** [comment]
confirmed that comms is working and I can send messages between drones.

I'm trying to testing the case when msgs stop dropping but it seems like it's always able to deliver the msgs?

Here's my setup with `quadrotor_1` at x=2000 and `quadrotor_2` at x=-2000 (notes onces the drone is spawned it drops to the ocean and becomes static so you won't be able to move them afterwards)

```
ros2 launch ros_ign_gazebo ign_gazebo.launch.py ign_args:="-v 4 -r simple_demo.sdf"

ros2 launch mbzirc_ign spawn.launch.py name:=quadrotor_1 world:=simple_demo model:=mbzirc_quadrotor type:=uav x:=2000 y:=0 z:=1.3 R:=0 P:=0 Y:=0

ros2 launch mbzirc_ign spawn.launch.py name:=quadrotor_2 world:=simple_demo model:=mbzirc_quadrotor type:=uav x:=-2000 y:=0 z:=1.3 R:=0 P:=0 Y:=0

ros2 topic pub quadrotor_1/tx ros_ign_interfaces/Dataframe '{src_address: "quadrotor_1", dst_address: "quadrotor_2"}'

ros2 topic echo /quadrotor_2/rx
```

**Comment by iche033** [comment]
Interesting.. I tried modifying the `publisher` example in ign-gazebo to publish data over comms from `quadrotor_1` to `quadrotor_2` and I see the expected behavior. However, if just do it over command line, the data always goes through:

```bash
while true; do ign topic -t "/broker/msgs" -m ignition.msgs.Dataframe -p "src_address: 'quadrotor_1', dst_address: 'quadrotor_2'"; done
```

**Comment by caguero** [comment]
> Interesting.. I tried modifying the `publisher` example in ign-gazebo to publish data over comms from `quadrotor_1` to `quadrotor_2` and I see the expected behavior. However, if just do it over command line, the data always goes through:
> 
> ```shell
> while true; do ign topic -t "/broker/msgs" -m ignition.msgs.Dataframe -p "src_address: 'quadrotor_1', dst_address: 'quadrotor_2'"; done
> ```

The command line doesn't fill the data field. I wonder if it's related...

**Comment by iche033** [comment]
ok with help from @caguero, this is now fixed in the upstream PR: https://github.com/ignitionrobotics/ign-gazebo/pull/1428

**Review by iche033 — APPROVED** [review]
made some minor flake8 style changes, fixed tests in [5ec3495](https://github.com/osrf/mbzirc/pull/82/commits/5ec349521f237c32372233d5622e08c5fa3e012a)

this looks good to me. We'll just need to wait for https://github.com/ignitionrobotics/ros_ign/pull/239

**Pull request merged**
