### PR TITLE
Add Coast world

### PR DESCRIPTION
**Pull request by iche033**
Depends on:
* #35
* https://github.com/ignitionrobotics/ign-gazebo/pull/1275

Adds a new world with a new [Beach](https://app.ignitionrobotics.org/OpenRobotics/fuel/models/Beach) and [Coast Waves](https://app.ignitionrobotics.org/OpenRobotics/fuel/models/Coast%20Waves) model. 

The beach model is roughly 5.9km by 1.67km, and the waves model is 8km by 8km

I set the absolute bounds of this world to be 8km by 8km. The competition area is much smaller (10km2) and will have a geofence around the area (TBD).

Other changes:
* I made water level consistent at z=0 in both simple_demo.sdf and coast.sdf world mainly so that it's easier to configure Surface plugin's `<fluid_level>`. 
* I moved the Surface and Hydrodynamics plugins from `Vessel A` to the world file. This is because a couple of `wavefield` params are dependent of the size of the world. These field are now populated using ERB. Note: You'll need to clear your fuel cache.
* updated WaveVisual system to parse more shader parameters

To test:

```bash
# the beach env will download new models and it takes some time to load on the gui side
ros2 launch ros_ign_gazebo ign_gazebo.launch.py ign_args:="-v 4 -r coast.sdf"

# spawn usv in coast world
ros2 launch mbzirc_ign spawn.launch.py name:=usv world:=coast model:=usv type:=usv x:=-1450 y:=0 z:=0.3 R:=0 P:=0 Y:=0

# spawn quadrotor - this will also take a while to load because the beach env is now being loaded on the server side
ros2 launch mbzirc_ign spawn.launch.py name:=quadrotor_1 world:=coast model:=mbzirc_quadrotor type:=uav x:=-1500 y:=0 z:=3.6 R:=0 P:=0 Y:=0 slot0:=mbzirc_hd_camera slot1:=mbzirc_rgbd_camera
```

Screenshot from 2022-02-08 17-58-28

**Update:**

Updated to use smaller and optimized version of wave model. The whole world is shown below with the competition area visualized in green.

mbzirc_competition_area

**Note to self**: Update wiki with new UAV / USV spawn positions after this PR is merged.

Signed-off-by: Ian Chen <ichen@osrfoundation.org>

### CODE REVIEW

**Review by caguero — APPROVED** [review]
Works for me!

**Comment by iche033** [comment]
> I see the following error messages when spawning the UAV:

I get those too. If I remember correctly, @mjcarroll mentioned that those error msgs are safe to ignore?

**Comment by caguero** [comment]
> > I see the following error messages when spawning the UAV:
> 
> I get those too. If I remember correctly, @mjcarroll mentioned that those error msgs are safe to ignore?

Oh I see, feel free to ignore them if are not new to this pull request.

**Comment by mjcarroll** [comment]
> I get those too. If I remember correctly, @mjcarroll mentioned that those error msgs are safe to ignore?

Yes, they are purely on the GUI side and should be a non-issue is my understanding.

**Pull request merged**
