### PR TITLE
Add ROS API tests

### PR DESCRIPTION
**Pull request by iche033**
Set up a ROS API test that verifies data are published over the UAV sensor topics

Code for testing ROS topics are adapted from `ros_ign_bridge`

To run the tests:

```
colcon test --merge-install --event-handlers console_direct+ --packages-select mbzirc_ros
```

Note: the test lets ignition gazebo run for 15000 iterations (15 sim seconds) then exits. I need to figure out a better way to kill the ignition process as soon as the gtest checks are done instead of running for fix number of iterations.

### CODE REVIEW

**Review by caguero — COMMENTED** [review]
Is it expected to get tests failing?

```
The following tests FAILED:
	  1 - test_launch_test_ros_api.launch.py (Failed)
	  2 - copyright (Failed)
	  4 - cpplint (Failed)
	  5 - flake8 (Failed)
	  8 - uncrustify (Failed)
```

**Comment by iche033** [comment]
oh no that's not expected. Hmm, weird I'll need to take another look.

**Comment by iche033** [comment]
I disabled linting in 598e2e7 since I'm following the ignition coding style as opposed to ROS. 

That should fix all the test except `test_launch_test_ros_api.launch.py (Failed)`. Test failure means data are not received on the ROS topics. The test is passing locally for me so my current guess is timing differences. Could you paste the console output from running the test?

**Comment by mjcarroll** [comment]
Mine is failing as well. There is a lot of output, but this is probably the most relevant part:

```
1: [create-5] [INFO] [1642086692.091766268] [ros_ign_gazebo]: Timed out when getting world names.
```

**Comment by iche033** [comment]
looks like rendering sensors are causing segfaults on github actions. I disabled them for now on github and build is passing.

To run rendering tests locally just set env variable `DISPLAY_TEST=1`

This is ready for another review

**Comment by j-rivero** [comment]
Now that #27 is merged, I think that we are in good moment not to duplicate the Dockefile and use the existing one. That has many benefits: less maintenance on changes, the Docker layer to be used while releasing is evaluated on every change, etc.

**Comment by j-rivero** [comment]
> Now that #27 is merged, I think that we are in good moment not to duplicate the Dockefile and use the existing one. That has many benefits: less maintenance on changes, the Docker layer to be used while releasing is evaluated on every change, etc.

I've implemented this in 1ae36c7

**Comment by iche033** [comment]
> I've implemented this in 1ae36c7

thanks! looks good to me

**Review by j-rivero — APPROVED** [review]

**Pull request merged**
