### PR TITLE
Refactor all UAV topics into a single bridge

### PR DESCRIPTION
**Pull request by mjcarroll**
Signed-off-by: Michael Carroll <michael@openrobotics.org>

### CODE REVIEW

**Comment by iche033** [comment]
hmm weird that I don't get the data on the ROS2 side.  However if I change the everything to `BIDIRECTIONAL` then I am able to ros2 echo data. Does this happen to you?

I'm testing in simple demo world with a quad rotor:

```
ros2 launch ros_ign_gazebo ign_gazebo.launch.py ign_args:="-v 4 -r simple_demo.sdf

ros2 launch mbzirc_ign spawn.launch.py name:=quadrotor_1 world:=simple_demo model:=mbzirc_quadrotor type:=uav x:=-0 y:=0 z:=1.2 R:=0 P:=0 Y:=0 slot3:=mbzirc_hd_camera
```

**Comment by mjcarroll** [comment]
> Does this happen to you?

Checking

**Comment by mjcarroll** [comment]
This commit had the bridging symbols backwards, I may have fixed it right after in my other development.

**Comment by iche033** [comment]
nice, it's working, and CI is passing

**Review by iche033 — APPROVED** [review]

**Pull request merged**
