### PR TITLE
Add all item models to the coast world

### PR DESCRIPTION
**Pull request by iche033**
Added various small and large item objects on the vessels.

~~I'm opening this PR for visibility first. There is still one small item model to be created. Once that's done, I'll swap out the small items on one of the vessels with the new one.~~ **Update** All items are available on Fuel. This is ready for review

I noticed a drop in RTF from 9x% to 5x% after including all 28 item models into the world (7 vessels with 4 items each). So I added detachable joints between the item models to reduce cost of collision checking. Now I'm getting 8x%~9x% RTF. The joints for the item models on top of the target vessel are detached once the target vessel is identified.

Other notes: 
* Creating a detachable joint between the items and the vessel (with child model being the vessel) seems to cause the surface or hydrodynamics plugin to apply the effect to the incorrect body causing weird vessel motion. So item models are not attached to vessel.
* Each link seems to be able to hold one 1 detachable joint. So the items on a vessel chained together, i.e. small object <-> small object duplicate <-> large object <-> large object duplicate

To test:

1. launch simple_demo world and try moving any item models on Vessel A. You should see that 4 item models are attached together
1. Publish a detach message and try again:

    ```
    ign topic -t "/Vessel_A/detach" -m ignition.msgs.Empty -p "unused: true
    ```

1. launch coast world and check all item models are correctly placed on top of the vessels.

### CODE REVIEW

**Comment by iche033** [comment]
All items are now available on Fuel. This is ready for review

**Comment by mjcarroll** [comment]
> launch simple_demo world and try moving any item models on Vessel A. You should see that 4 item models are attached together

I can only move `large_dry_box_a_duplicate`, which moves all 4 boxes.  Moving the others doesn't have an impact (they jump back).

**Comment by iche033** [comment]
> I can only move large_dry_box_a_duplicate, which moves all 4 boxes. Moving the others doesn't have an impact (they jump back).

yeah I think that's the expected behavior due to the way they are connected. They should not move individually

**Comment by mjcarroll** [comment]
> They should not move individually

Okay, that matches the behavior I'm seeing. :+1:

**Comment by mjcarroll** [comment]
Confirmed 
* Vessel A has 2 blue small boxes and 2 large boxes
2022-04-13T16:21:48 320339871
* Vessel B has 2 small cases and 2 large gray boxes
2022-04-13T16:24:37 989740607
* Vessel C has 2 small dry bags and 2 large ammo cans
2022-04-13T16:24:12 620368210
* Vessel D has 2 blue small boxes and 2 large crates
2022-04-13T16:23:51 708952407
* Vessel E has 2 small dry bags and 2 dry boxes
2022-04-13T16:23:29 534892013
* Vessel F has 2 small cases and 2 large ammo cans
2022-04-13T16:22:52 453879873
* Vessel G has 2 small dry bags and 2 large crates
2022-04-13T16:22:21 976828914

**Review by mjcarroll — APPROVED** [review]

**Comment by iche033** [comment]
thanks for checking!

> Vessel A has 2 blue small boxes and 2 large boxes

btw, that looks like the old Vessel A model. The seats are removed the in the latest version

**Pull request merged**
