### PR TITLE
Add wind effect

### PR DESCRIPTION
**Pull request by iche033**
Add wind effect - affects all vehicles including target vessels

To test, launch simple_demo or coast world, spawn the USV and see it drift in x direction over time, e.g.

```bash
# launch simple_demo world
ros2 launch ros_ign_gazebo ign_gazebo.launch.py ign_args:="-v 4 -r simple_demo.sdf"

# Spawn USV. Open ign-gazebo's component inspector and pay attention the USV's X position
ros2 launch mbzirc_ign spawn.launch.py name:=usv world:=simple_demo model:=usv type:=usv x:=15 y:=0 z:=0.3 R:=0 P:=0 Y:=0
```

For UAVs, you'll need to make it take off first to see it drift in x direction.

```bash
# spawn quadrotor
ros2 launch mbzirc_ign spawn.launch.py name:=quadrotor_1 world:=simple_demo model:=mbzirc_quadrotor type:=uav x:=1 y:=2 z:=1.05 R:=0 P:=0 Y:=0 slot0:=mbzirc_hd_camera

# take off. 
ros2 topic pub --once /quadrotor_1/cmd_vel geometry_msgs/msg/Twist '{linear: {x: 0.0,y: 0.0, z: 0.5}, angular: {x: 0.0, y: 0.0, z: 0.0}}'

# make it hover. Open ign-gazebo's component inspector and monitor UAV's x position
ros2 topic pub --once /quadrotor_1/cmd_vel geometry_msgs/msg/Twist '{linear: {x: 0.0,y: 0.0, z: 0.0}, angular: {x: 0.0, y: 0.0, z: 0.0}}'

```

Signed-off-by: Ian Chen <ichen@osrfoundation.org>

### CODE REVIEW

**Review by caguero — COMMENTED** [review]
Looks good to me. Should we enable wind for the fixed wing?

**Review by caguero — COMMENTED** [review]
Out of curiosity, where is the wind enabled for the target vessel?

**Comment by iche033** [comment]
I added the `enable_wind` flag directly to the model online, e.g https://app.ignitionrobotics.org/OpenRobotics/fuel/models/Vessel%20A

**Comment by iche033** [comment]
> Should we enable wind for the fixed wing?
ok yeah, I'll do that

**Comment by iche033** [comment]
> > Should we enable wind for the fixed wing?
> 
> ok yeah, I'll do that

done in [6e5a67a](https://github.com/osrf/mbzirc/pull/43/commits/6e5a67a68c776c771a8f71469645317416b20d4b)

**Review by caguero — APPROVED** [review]

**Pull request merged**
