### PR TITLE
Arm custom arm mounting slots

### PR DESCRIPTION
**Pull request by caguero**
Added an extra parameter `arm_slot` that can be used to attach the arm into a custom mounting slot.

Here's the accompanying tutorial:
https://github.com/osrf/mbzirc/wiki/Custom-Arm-Mount

The tutorials shows hot to create a new custom arm slot. Follow the tutorial and you should be able to spawn the arm in the right side of the USV. The default behavior (no `arm_slot` parameter) should still work.

### CODE REVIEW

**Review by mjcarroll — APPROVED** [review]
Tested working for me.  There is only one available arm slot in the current configuration, though.

**Comment by iche033** [comment]
looks good to me. 

About this not in the wiki page:

> Note that the parameter arm_slot should match the name of an existing arm slot. If this parameter is not present, it defaults to arm_slot_0.

we specify the index of the slot not the name right and it defaults to `0`?

**Review by iche033 — APPROVED** [review]

**Comment by caguero** [comment]
> looks good to me.
> 
> About this note in the wiki page:
> 
> > Note that the parameter arm_slot should match the name of an existing arm slot. If this parameter is not present, it defaults to arm_slot_0.
> 
> we specify the index of the slot not the name right and it defaults to `0`?

That's right, 

> looks good to me.
> 
> About this note in the wiki page:
> 
> > Note that the parameter arm_slot should match the name of an existing arm slot. If this parameter is not present, it defaults to arm_slot_0.
> 
> we specify the index of the slot not the name right and it defaults to `0`?

Good point, I updated the wiki.

**Comment by caguero** [comment]
> Tested working for me. There is only one available arm slot in the current configuration, though.

That was on purpose as the teams should create the arm slots as they wish.

**Pull request merged**
