### PR TITLE
Limits the maximum thrust to 8 knots

### PR DESCRIPTION
**Pull request by arjo129**
This PR adds a limit to the USV thruster and some unit tests to test the limit. The USV model has also been made such that only the visual is rotated so that the hydrodynamics can be reasoned about. For derivation of the math see here: https://colab.research.google.com/drive/1xV0rw1rqBSU0RdVYTVUkHir7BHADQIWn?usp=sharing

### CODE REVIEW

**Comment by iche033** [comment]
Nice, changes look good to me. Just need to rotate the collisions:

usv_collisions

**Comment by arjo129** [comment]
Is there a reason why we were using boxes to estimate the mesh? Can we just use the same mesh for visuals and collision?

**Comment by caguero** [comment]
> Is there a reason why we were using boxes to estimate the mesh? Can we just use the same mesh for visuals and collision?

It's more efficient to compute collisions.

**Comment by arjo129** [comment]
Fixed the collisions this should be good to go.

**Review by iche033 — APPROVED** [review]

**Pull request merged**
